### ISSUE TITLE
Hello-World Sample crashes!

### ISSUE THREAD

**Issue by wahrwolf** [drsam94/Spl#9]
The current master branch is not able to compile the Hello-World example from the spl docs.

The last functioning commit seems to be [adbddf3a7357e1dcfe3b7a2c602f3086b974413d]

As a fix i manually reverted the line 320+ in the splc.py to what it hat before that commit.

Since I blindly hacked it, I have no idea of any side affects and would love to see a cleaner solution :D

**Comment by drsam94** [comment]
I just pushed a change that should fix it for good now; It looks like my previous hasty fix of the handling of "as" led to an off-by-one error, with the first char of the following phrase being cut off (note that the off-by-one error didn't matter for "as" because the next char was always a space, but did for " as "). This wasn't an issue with most programs because it's common to start expressions with meaningless words, especially "the", but hello world used an "as Hamlet" which caused the issue.
